# Generated by Django 6.0.3 on 2026-03-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked')], max_length=50),
        ),
    ]
