# Generated by Django 6.0.3 on 2026-03-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Langauge', 'verbose_name_plural': 'Languagedds'},
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster_image',
            field=models.ImageField(null=True, upload_to='posters'),
        ),
    ]
