# Generated by Django 6.0.3 on 2026-03-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_genre_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
    ]
